### ISSUE TITLE
ews-missing-executables - instructions unclear

### ISSUE THREAD

**Issue by julian-hoch** [pprevos/emacs-writing-studio#26]
The book mentions that the function "ews-missing-executables" is used to check for missing executables.  I assume this is run automatically on startup, but that is unclear - at first I thought I have to manually run this, and then got confused that it is 
a) not interactive and
b) has mandatory parameters.
So, I think this should be made clear.  Why mention the function name at all, if you cannot call it manually? Also, a clear message in the log if everything was found could be helpful.

**Comment by pprevos** [comment]
Hi @julian-hoch,

Thanks for the feedback.

This is not an interactive function because it requires a complex list of packages to test. It runs automatically when the EWS init file is loaded.

I have updated the function to include a message when all listed executable files are found. I have also clarified the relevant paragraph in chapter 4 for future editions.

regards

P:)
