### ISSUE TITLE
Hiding warnings that may appear during initial setup

### ISSUE THREAD

**Issue by grtcdr** [pprevos/emacs-writing-studio#3]
Hi there,

I just took this for a spin and noticed that, during setup i.e. after packages are initially installed from their the archives, the `*Warnings*` buffer proceeded to harass me with trivial  non-errors. I think novice Emacs users and authors with no programming experience might find this behavior a bit terrifying.

![2023-09-27T12:43:14,894895115+01:00](https://github.com/pprevos/emacs-writing-studio/assets/35816711/09bc5c3d-79a1-4a1e-8859-61d0a7e7e4b0)

Would you be open to setting `warning-minimum-level` to `:error`? I could open a pull request with the appropriate change if you're willing to move forward with it.

Thank you so much for this package and for all the lovely writer-centric articles you've been publishing.

**Comment by pprevos** [comment]
Hi Andreas,

Great suggestion, I did not know that such a setting existed. Is this something to be set in each package declaration or is there a variable?

Please submit a pull request so you get the credit in the repo.

**Comment by pprevos** [comment]
Apologies Taha, I am mixing-up messages.

Using the `use-package` macro for one line of code is perhaps a bit much. 

Perhaps it best fits with the `ews-packages.el` module. I include these modules in my web pages so that I keep referential integrity between the code and the published pages. I generate `init.el` with a script.
